### ISSUE TITLE
Adjust Calico resource consumption for 2 CPU instances

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma-infrastructure-manager#273]
**Description**

The default configuration applied by Gardener for Calico is not suitable for small-sized clusters). It can lead to overcommit CPUs and make such clusters quite inefficient (see # 5719)

KIM has to apply following adjustments in the network configuration for K8s cluster:

1. *For 2CPU clusters created for NON-enterprise plans (trials/free plans):*
    a. Disable typha:
    ```
    networking:
      type: calico
      providerConfig:
        overlay:
          enabled: false
        typha:
         enabled: false
    ```
    b. Adjust CPU limits
    The calico-node daemonset has to be patched to request 30m CPU instead of 250m gardener-hardcoded default value.

3. *For 2 CPU clusters created using an enterprise plan:*

    The calico-node daemonset has to be patched to request 100m CPU instead of 250m gardener-hardcoded default value. However the calico-typha must NOT be disabled on enterpeise plan runtimes.

**Reasons**

Avoid CPU overcommitments caused by Calico on 2-CPU nodes.

**Attachments**
