### ISSUE TITLE
Reply structured error messages in RuntimeCR to KEB

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma-infrastructure-manager#630]
**Description**

KIM is currently replying plain strings to KEB in RuntimeCRs. This has several limitations and makes it hard to provide well formatted and informative error messages to our BTP customers.

We agreed to use structured data in the future (e.g. JSON) in our error messages. This has several advantages:

* Provide metadata about error cases (e.g. error-key, where the error occurred,, timestamp etc.)
* Deliver more flexible error messages which can be translated in the UI smoothly (distinguish between static error string and it's dynamic parts)
* Make the error processable by machines 
etc.

Example:

```
"error": {
    "key": "kim.error.network.timeout",
    "msg": "Timeout occurred during network communication",
    "source": "this was the context where it happened", //tbc: do we need such information?
}
```

Alternatively: we don'r use dedicated error objects, instead we use the existing conditions in our API to provide proper error message. See https://github.com/kyma-project/infrastructure-manager/blob/main/api/v1/runtime_types.go#L74-L101:

```
status:
  conditions:
  - lastTransitionTime: "2025-05-13T08:44:02Z"
    message: Runtime processing completed successfully
    reason: ConfigurationCompleted
    status: "True"
    type: Provisioned
  - lastTransitionTime: "2024-11-18T20:14:59Z"
    message: Gardener Cluster CR is ready.
    reason: GardenerClusterCRReady
    status: "True"
    type: KubeconfigReady
  - lastTransitionTime: "2024-11-18T20:15:01Z"
    message: OIDC configuration completed
    reason: OidcConfigured
    status: "True"
    type: OidcConfigured
  - lastTransitionTime: "2024-11-18T20:15:06Z"
    message: Cluster admin configuration complete
    reason: AdministratorsConfigured
    status: "True"
    type: Configured
```

AC:
- [ ] Discuss within Framefrog,Gophers and SREs (see #653) to agree on their requirements and how we will provide a structured feedback for them
   - [ ] Setup a call with @kyma-project/gopher, @kyma-project/framefrog + SRE and document the result how the last erros will be exposed in RuntimeCR
- [ ] Start using structured error repsonses for following cases:
    - [ ] Too small / big network configured by customer

**Reasons**

Enhance error messages provided to KEB to improve UX in BTP Cockpit / enable SRE to analyse failure cases.

**Attachments**
