### ISSUE TITLE
Expose shoot last operation errors

### ISSUE THREAD

**Issue by ebensom** [kyma-project/kyma-infrastructure-manager#653]
**Description**

In the  waiting for shoot creation and reconciliation FSM steps, in case the shoot `lastOperation.state` is `Progressing`, `Error` or `Failed`, the `lastErrors` should always be logged by KIM. 

Furthermore the `lastErrors` should also conveyed and exposed in the `Runtime CR` status block, so that KEB and SRE tooling could parse it and further process it. 

One example for the shoot lastErrors to be captured and exposed by KIM:

```
status:
  lastOperation:
    description: Waiting until Kubernetes API server rolled out
    lastUpdateTime: '2025-02-07T13:50:42Z'
    progress: 25
    state: Processing
    type: Create
  lastErrors:
    - description: "task \"Waiting until shoot worker nodes have been reconciled\" failed: Error while waiting for Worker shoot--kyma--f6c50cd/f6c50cd to become ready: error during reconciliation: Error reconciling Worker: failed while waiting for all machine deployments to be ready: machine(s) failed: 1 error occurred: \"shoot--kyma--f6c50cd-cpu-worker-0-z3-98968-l5nt9\": Cloud provider message - machine codes error: code = [ResourceExhausted] message = [InsufficientInstanceCapacity: We currently do not have sufficient m6i.16xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m6i.16xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1b, eu-central-1c.\n\tstatus code: 500, request id: 2ba83cd3-4a2c-42c0-a00e-142bee1f9316]"
      taskID: Waiting until shoot worker nodes have been reconciled
      codes:
        - ERR_INFRA_RESOURCES_DEPLETED
```

AC:
- [ ] Log received errors from Gardener into KIM logs (currently, are not errors from Gardener tracked in our log output)
- [ ] Update the status-section in RuntimeCR by adding a `lastErrors` string-field to it and track the last received error in this field

**Reasons**

Gap in post-mortem troubleshooting. In case the shoot cluster is deleted, the only way to perform forensic analysis why a shoot could not be reconciled by Gardener is to ask Gardener DoD about shoot-controller-manager logs. This is a manual tedious and time-consuming process.

The enhancement should be treated with high priority as this gap is identified by a post-mortem action item: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=5035150267

**Attachments**

**Comment by tobiscr** [comment]
WE have also to expose such information during the reconciliation to KEB!

**Comment by Disper** [comment]
#1059 is now available under `pr-deploy`  on DEV.

Few examples of statuses:

### lastErrors present due to incorrect machineType:

``` yaml
conditions:
  - lastTransitionTime: "2025-08-22T07:24:39Z"
    message: Retryable gardener errors during cluster reconcile
    reason: Pending
    status: Unknown
    type: Provisioned
  - lastTransitionTime: "2025-08-22T07:20:53Z"
    message: Gardener Cluster CR is ready.
    reason: GardenerClusterCRReady
    status: "True"
    type: KubeconfigReady
  - lastTransitionTime: "2025-08-22T07:20:57Z"
    message: OIDC and kyma-provisioning-info configuration completed
    reason: OidcAndConfigMapsConfigured
    status: "True"
    type: OidcAndConfigMapConfigured
  - lastTransitionTime: "2025-08-22T07:20:57Z"
    message: Cluster admin configuration complete
    reason: AdministratorsConfigured
    status: "True"
    type: Configured
provisioningCompleted: true
shootLastErrors:
  - codes:
      - ERR_CONFIGURATION_PROBLEM
    description: "task \"Waiting until shoot worker nodes have been reconciled\" failed: Error while waiting for Worker shoot--kyma-dev--md-lop2/md-lop2 to become ready: error during reconciliation: Error reconci
ling Worker: failed while waiting for all machine deployments to be ready: machine(s) failed: 3 errors occurred: [\"shoot--kyma-dev--md-lop2-new-worker-1-z1-7876f-q4xb2\": Cloud provider message - machine codes e
rror: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your requested Availability Zone (ap-southeast-2b). Please retry your request by not specifying an Avai
lability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 8aab66b0-3b7c-4ee6-977e-ad1538a1ba5a], \"shoot--kyma-dev--md-lop2-new-worker-1-z1-7876f-fq5tc\": Cloud provider message
 - machine codes error: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your requested Availability Zone (ap-southeast-2b). Please retry your request by not
specifying an Availability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 25bb4f90-f1db-4054-95bd-2874d2aabd75], \"shoot--kyma-dev--md-lop2-new-worker-1-z1-7876f-mqllj\": Clou
d provider message - machine codes error: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your requested Availability Zone (ap-southeast-2b). Please retry yo
ur request by not specifying an Availability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 8693d7ce-a759-4fec-879d-12d7ea5631b9]]"
    lastUpdateTime: "2025-08-22T07:25:59Z"
    taskID: Waiting until shoot worker nodes have been reconciled
shootLastOperation:
  description: "Flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Waiting until shoot worker nodes have been reconciled\" failed: Error while waiting for Worker shoot--kyma-dev--md-lop2/md-lo
p2 to become ready: error during reconciliation: Error reconciling Worker: failed while waiting for all machine deployments to be ready: machine(s) failed: 3 errors occurred: [\"shoot--kyma-dev--md-lop2-new-worke
r-1-z1-7876f-q4xb2\": Cloud provider message - machine codes error: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your requested Availability Zone (ap-sout
heast-2b). Please retry your request by not specifying an Availability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 8aab66b0-3b7c-4ee6-977e-ad1538a1ba5a], \"shoot--kyma-dev-
-md-lop2-new-worker-1-z1-7876f-fq5tc\": Cloud provider message - machine codes error: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your requested Availabi
lity Zone (ap-southeast-2b). Please retry your request by not specifying an Availability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 25bb4f90-f1db-4054-95bd-2874d2aabd75],
\"shoot--kyma-dev--md-lop2-new-worker-1-z1-7876f-mqllj\": Cloud provider message - machine codes error: code = [Internal] message = [Unsupported: Your requested instance type (g6.xlarge) is not supported in your
requested Availability Zone (ap-southeast-2b). Please retry your request by not specifying an Availability Zone or choosing ap-southeast-2a, ap-southeast-2c.\n\tstatus code: 400, request id: 8693d7ce-a759-4fec-87
9d-12d7ea5631b9]]]"
  lastUpdateTime: "2025-08-22T07:25:59Z"
  progress: 88
  state: Failed
  type: Reconcile
state: Pending
```

### Error happening during cluster creation

``` yaml 
conditions:
  - lastTransitionTime: "2025-08-22T09:52:40Z"
    message: Shoot creation in progress
    reason: Pending
    status: Unknown
    type: Provisioned
shootLastErrors:
  - description: 'task "Waiting until shoot worker nodes have been reconciled" failed: Error while wait
ing for Worker shoot--kyma-dev--md-lop2/md-lop2 to become ready: error during reconciliation: Error rec
onciling Worker: failed while waiting for all machine deployments to be ready: retry failed with contex
t deadline exceeded, last error: Waiting until machines are available (0/3 desired machine(s) available
, 3/3 machine(s) updated, 3 machine(s) pending, 0/3 machinedeployments available)...'
    lastUpdateTime: "2025-08-22T10:06:46Z"
    taskID: Waiting until shoot worker nodes have been reconciled
shootLastOperation:
  description: Waiting until worker resource status is updated with latest machine deployments
  lastUpdateTime: "2025-08-22T10:07:37Z"
  progress: 83
  state: Processing
  type: Create
state: Pending
```

### When the cluster self-heals from the error

``` yaml
conditions:
  - lastTransitionTime: "2025-08-22T10:08:41Z"
    message: Shoot creation completed
    reason: ShootCreationCompleted
    status: "True"
    type: Provisioned
  - lastTransitionTime: "2025-08-22T10:08:51Z"
    message: Gardener Cluster CR is ready.
    reason: GardenerClusterCRReady
    status: "True"
    type: KubeconfigReady
  - lastTransitionTime: "2025-08-22T10:08:53Z"
    message: OIDC and kyma-provisioning-info configuration completed
    reason: OidcAndConfigMapsConfigured
    status: "True"
    type: OidcAndConfigMapConfigured
  - lastTransitionTime: "2025-08-22T10:08:53Z"
    message: Cluster admin configuration complete
    reason: AdministratorsConfigured
    status: "True"
    type: Configured
provisioningCompleted: true
shootLastOperation:
  description: Shoot cluster has been successfully reconciled.
  lastUpdateTime: "2025-08-22T10:08:04Z"
  progress: 100
  state: Succeeded
  type: Create
state: Ready
```
